package ru.oz.mytutorials.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2015-08-09T15:46:20.969+04:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://service.mytutorials.oz.ru/", name = "BankAccountService")
@XmlSeeAlso({ObjectFactory.class})
public interface BankAccountService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://service.mytutorials.oz.ru/", className = "ru.oz.mytutorials.service.GetUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://service.mytutorials.oz.ru/", className = "ru.oz.mytutorials.service.GetUserDetailsResponse")
    public ru.oz.mytutorials.service.UserDetails getUserDetails(
        @WebParam(name = "userMyName", targetNamespace = "")
        java.lang.String userMyName
    );

    @RequestWrapper(localName = "addUserDetails", targetNamespace = "http://service.mytutorials.oz.ru/", className = "ru.oz.mytutorials.service.AddUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "addUserDetailsResponse", targetNamespace = "http://service.mytutorials.oz.ru/", className = "ru.oz.mytutorials.service.AddUserDetailsResponse")
    public void addUserDetails(
        @WebParam(name = "userDetails", targetNamespace = "")
        ru.oz.mytutorials.service.UserDetails userDetails
    );
}
