package ru.oz.mytutorials.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2015-08-09T15:46:20.977+04:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "BankAccountServiceService", 
                  wsdlLocation = "file:/D:/Packet/MyTutors/BankAccounWebService/src/main/resources/BankAccountService.wsdl",
                  targetNamespace = "http://service.mytutorials.oz.ru/") 
public class BankAccountServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.mytutorials.oz.ru/", "BankAccountServiceService");
    public final static QName BankAccountServicePort = new QName("http://service.mytutorials.oz.ru/", "BankAccountServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Packet/MyTutors/BankAccounWebService/src/main/resources/BankAccountService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankAccountServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Packet/MyTutors/BankAccounWebService/src/main/resources/BankAccountService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankAccountServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankAccountServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAccountServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BankAccountServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BankAccountServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BankAccountServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BankAccountService
     */
    @WebEndpoint(name = "BankAccountServicePort")
    public BankAccountService getBankAccountServicePort() {
        return super.getPort(BankAccountServicePort, BankAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankAccountService
     */
    @WebEndpoint(name = "BankAccountServicePort")
    public BankAccountService getBankAccountServicePort(WebServiceFeature... features) {
        return super.getPort(BankAccountServicePort, BankAccountService.class, features);
    }

}
